export {
  productCategorySchema,
  headphoneSpecsSchema,
  smartwatchSpecsSchema,
  earbudsSpecsSchema,
  speakerSpecsSchema,
  productSpecsSchema,
  connectivitySchema,
  batteryLifeSchema,
  productVariantSchema,
  createProductSchema,
  cartItemSchema,
  reviewRatingsSchema,
  createReviewSchema,
  orderStatusSchema,
  shippingAddressSchema,
  orderItemSchema,
  warrantySchema,
  createOrderSchema,
} from "./product";
